import Head from "next/head";
import Image from "next/image";
import phone from "../assets/mockup.png";
import Nav from "../components/nav";
import Spacer from "../components/spacer";
import Features from "../sections/features";
import Landing from "../sections/main";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Landing />
      <Spacer />
      <Spacer />
      <Features />
    </div>
  );
}
