import Head from "next/head";
import Image from "next/image";
import phone from "../assets/mockup.png";
import Footer from "../components/footer";
import Nav from "../components/nav";
import Spacer from "../components/spacer";
import Contact from "../sections/contact";
import Features from "../sections/features";
import Gallery from "../sections/gallery";
import Main from "../sections/main";
import Landing from "../sections/main";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portion - Simple. Good. Food.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <div className="space-y-14 md:space-y-28">
        <section id="top">
          <Main />
        </section>
        <section id="features">
          <Features />
        </section>
        <section id="gallery">
          <Gallery />
        </section>
        <Footer />
      </div>
    </div>
  );
}
